name: CI

on:
  push:
    tags:
      - 'v*'

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:

      - uses: actions/checkout@v3

      - name: Setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install and Build
        run: |
          npm install -g pnpm
          pnpm install
          npm run build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Registry
        run: docker login --username=${{ secrets.REGISTRY_USERNAME }} --password ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build Image
        run: |
          docker buildx build --push --platform linux/amd64,linux/arm64 -t jmpsvr/frontend:latest -t jmpsvr/frontend:${{ github.ref_name }} .